// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateEvents implements pgx.CopyFromSource.
type iteratorForCreateEvents struct {
	rows                 []CreateEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DomainID,
		r.rows[0].SessionID,
		r.rows[0].VisitorID,
		r.rows[0].Name,
		r.rows[0].Path,
		r.rows[0].Referrer,
		r.rows[0].LoadTime,
		r.rows[0].Ttfb,
	}, nil
}

func (r iteratorForCreateEvents) Err() error {
	return nil
}

func (q *Queries) CreateEvents(ctx context.Context, arg []CreateEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"domain_id", "session_id", "visitor_id", "name", "path", "referrer", "load_time", "ttfb"}, &iteratorForCreateEvents{rows: arg})
}
