// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AutocertCache struct {
	Key       string
	Data      []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Domain struct {
	DomainID   int32
	DomainName string
}

type Event struct {
	ID        int64
	Name      string
	DomainID  int32
	Path      string
	Referrer  string
	VisitorID string
	SessionID int64
	LoadTime  int32
	Ttfb      int32
	CreatedAt pgtype.Timestamptz
}

type Salt struct {
	Salt      pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID             int64
	UpdatedAt      pgtype.Timestamptz
	Duration       pgtype.Int4
	Bounce         bool
	ExitPath       string
	VisitorID      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DomainID       int32
	EntryPath      string
	Country        pgtype.Text
	Latitude       pgtype.Float8
	Longitude      pgtype.Float8
	Subdivision    pgtype.Text
	City           pgtype.Text
	Browser        pgtype.Text
	BrowserVersion pgtype.Text
	Os             pgtype.Text
	OsVersion      pgtype.Text
	Platform       pgtype.Text
	DeviceType     pgtype.Text
	Bot            bool
	ScreenW        pgtype.Int4
	ScreenH        pgtype.Int4
	Timezone       pgtype.Text
	PixelRatio     pgtype.Float8
	PixelDepth     pgtype.Int4
	UtmSource      pgtype.Text
	UtmMedium      pgtype.Text
	UtmCampaign    pgtype.Text
	UtmContent     pgtype.Text
	UtmTerm        pgtype.Text
}
