#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE picolytics;
    \c picolytics

    CREATE USER $POSTGRES_PICOLYTICS_USER WITH PASSWORD '$POSTGRES_PICOLYTICS_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE picolytics TO $POSTGRES_PICOLYTICS_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO picolytics;

    CREATE USER $POSTGRES_GRAFANA_USER WITH PASSWORD '$POSTGRES_GRAFANA_PASSWORD';
    GRANT CONNECT ON DATABASE picolytics TO $POSTGRES_GRAFANA_USER;
    GRANT USAGE ON SCHEMA public TO $POSTGRES_GRAFANA_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_PICOLYTICS_USER IN SCHEMA public GRANT SELECT ON TABLES TO $POSTGRES_GRAFANA_USER;
EOSQL
