{{- if .Values.picolytics.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "picolytics.serviceAccountName" . }}
  labels:
    {{- include "picolytics.labels" . | nindent 4 }}
  {{- with .Values.picolytics.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.picolytics.serviceAccount.automount }}
{{- end }}
