{
 "title": "Picolytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to Picolytics!\n\nPlease make this dashboard your own! Delete irrelevant graphs, add new ones, and make things look perfect."
   }
  },
  { "title": "Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Distinct visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct events.visitor_id) FROM events \nJOIN sessions ON events.session_id = sessions.id\nWHERE\n  $__timeFilter(events.created_at) AND sessions.bot = false;"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM sessions WHERE\n  $__timeFilter(sessions.created_at) AND sessions.bot = false;"
    }
   ]
  },
  {
   "title": "Total pageloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(events.id)\nFROM events\nJOIN sessions ON events.session_id = sessions.id\nWHERE $__timeFilter(events.created_at) AND sessions.bot = false;"
    }
   ]
  },
  {
   "title": "Session Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   avg(sessions.duration) FROM sessions WHERE\n  $__timeFilter(sessions.updated_at) AND sessions.bot = false;\n\n  \n"
    }
   ]
  },
  {
   "title": "Bounce Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE \n        WHEN COUNT(*) = 0 THEN NULL\n        ELSE (COUNT(*) FILTER (WHERE bounce) * 100.0) / COUNT(*)\n    END AS bounce_rate\nFROM\n    sessions\nWHERE\n    $__timeFilter(sessions.created_at) AND sessions.bot = false;\n"
    }
   ]
  },
  {
   "title": "Pageloads/visit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(view_count) AS average_views_per_visit\nFROM (\n    SELECT s.id, COUNT(e.id) AS view_count\n    FROM sessions s\n    JOIN events e ON s.id = e.session_id\n    WHERE s.bot = FALSE\n    AND e.name != 'ping'\n    AND $__timeFilter(s.updated_at)\n    GROUP BY s.id\n) AS session_views;"
    }
   ]
  },
  {
   "title": "Current sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFROM sessions\nWHERE $__timeFilter(sessions.created_at) \nAND sessions.bot = false\nAND updated_at > CURRENT_TIMESTAMP - '30 minutes'::interval;"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(events.created_at, $__interval),\n  domains.domain_name as domain,\n  COUNT(events.id) as \" \"\nFROM events\nJOIN domains ON events.domain_id = domains.domain_id\nWHERE\n  events.name = 'load'\n  AND $__timeFilter(events.created_at)\nGROUP BY 1, domains.domain_name\nORDER BY 1, domains.domain_name\n"
    }
   ]
  },
  {
   "title": "Session Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(sessions.updated_at, $__interval),\n  sessions.duration\nFROM sessions\nWHERE\n  $__timeFilter(sessions.updated_at) AND sessions.bot = false;\n"
    }
   ]
  },
  {
   "title": "Top Sources",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN referrer = '' THEN 'direct'\n        ELSE referrer\n    END AS referrer,\n    COUNT(DISTINCT visitor_id) AS visitors\nFROM\n    events\nWHERE\n    $__timeFilter(events.created_at)\nGROUP BY\n    CASE\n        WHEN referrer = '' THEN 'direct'\n        ELSE referrer\n    END\nORDER BY\n    visitors DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Top Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n    path,\n    COUNT(distinct visitor_id) AS visitors\nFROM\n    events\nWHERE referrer != ''\nAND \n  $__timeFilter(events.created_at)\nGROUP BY\n    path\nORDER BY\n    visitors DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Entry Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT entry_path AS path, COUNT(*) AS visitors\nFROM sessions\nWHERE bot = FALSE  -- Assuming you want to exclude bot sessions\nAND \n  $__timeFilter(sessions.created_at)\nGROUP BY path\nORDER BY visitors DESC\nLIMIT 10;  -- You can adjust the limit as needed\n"
    }
   ]
  },
  {
   "title": "Exit Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT exit_path AS path, COUNT(*) AS visitors\nFROM sessions\nWHERE bot = FALSE  -- Assuming you want to exclude bot sessions\nAND $__timeFilter(sessions.created_at)\nGROUP BY path\nORDER BY visitors DESC\nLIMIT 10;  -- Adjust the limit as needed"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude FROM sessions WHERE $__timeFilter(created_at) LIMIT 50 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "options": {
    "content": "# Links\n\n* [GitHub](https://github.com/nmcclain/picolytics)\n* <a target=\"_blank\" href='https://db-ip.com'>IP Geolocation by DB-IP</a>"
   }
  },
  {
   "title": "Picolytics Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events/sec (metric)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(picolytics_ingested_events)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Connections dropped by rate limiter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(picolytics_rate_limiter_drops)[$__interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "rate(picolytics_event_errors)[$__interval]",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "go_goroutines{job=\"picolytics\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue utilization %",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "picolytics_queue_utilization/picolytics_queue_size",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ingest Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "sum(increase(picolytics_ingest_latency_bucket[$__interval])) by (le) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Build info",
     "type": "table",
     "gridPos": { "h": 4, "w": 18, "x": 0, "y": 77 },
     "targets": [
      { "expr": "picolytics_build_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Host Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
     "options": {
      "content": "**Note**: This section will be empty unless you set `DISABLE_HOST_METRICS=false`.\n"
     }
    },
    {
     "title": "Host CPU Idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      { "expr": "picolytics_host_cpu_idle_pct", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Host Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      { "expr": "picolytics_host_load_one", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Host memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "picolytics_host_mem_total", "legendFormat": "{{job}}" },
      { "expr": "picolytics_host_mem_used", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}